[package]
name = "my_crate"
version = "0.1.0"
authors = ["Sean Tan <shaqsnake@gmail.com>"]
edition = "2018"
description = "My first crate."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
